### ISSUE TITLE
Kernel 4. support

### ISSUE THREAD

**Issue by haralambop** [schoebel/mars#11]
Hi Thomas,

Any plan for kernel 4 support?

Thanks 

Andreas

**Comment by schoebel** [comment]
Yes, but currently only beta / experimental. See branch WIP-compatibility.

It needs not only rebasing to the newest light 0.2.y branch, but also
some more testing.

It seemed to run stable with vanilla kernel 4.2.

There were some compatibility problems with kernel 4.4, and these
_seemed_ to be fixed in December / January, but I am not 100% sure due
to lack of time for really extensive testing.

I need more time. More than 24h/d ;) Then I will push a (hopefully)
better version ;)

Cheers,

Thomas

**Comment by astinf** [comment]
Thank you Thomas!

What's about this Linux gentoo4 4.1.15-gentoo-r1?


I don't see any vanila-4.1 directory in branch WIP-compatibility.

**Comment by schoebel** [comment]
The WIP-compatibility is supposed to compile both with and without
prepatch. It _should_ adapt automatically.

However, not all combinations are really tested. No guarantees at the
moment.

Porting the prepatch to newer kernels is almost trivial. If you cannot
do it yourself, I will try to get some time at the weekend.

It would be nice if some people from the opensource community would
start supporting me at development level.

**Comment by schoebel** [comment]
The main problem is that the block layer in the kernel changes all the
time, continuously ... ;)

Currently, there seem to be even two different *-next versions somewhere
floating around.

Hopefully this will stabilize somewhen, otherwise my WIP-compatibility
branch will never be completed ;)

Some developer capacity from the community would be highly appreciated
for all of this tedious adaptation and versioning work.

**Comment by astinf** [comment]
thank you thomas 

i will revert back to 3.9 until you develop any stable version for 4xxx 

BTW.

Mars is a great product

My compliments

Andreas
