### ISSUE TITLE
Kernel 3.16 pre-patch for Debian Jessie ?

### ISSUE THREAD

**Issue by seb-esperanto** [schoebel/mars#14]
Hello Hallo,
I Just discovered Mars, looks very interesting !

Kernel pre-patches are available until 3.15,
unfortunately current Debian stable release Jessie ships with 3.16...

Do you think I could use 3.15 pre-patch with 3.16 kernel source,
or should I wait for 3.16 pre-patch to be available ?

Thank you so much for your work !
sébastien

**Comment by schoebel** [comment]
Hi Sebastien,

I just checked that the generic pre-patch for kernel 3.14 also applies to vanilla 3.16.7 with some small fuzz. I did not test the Debian flavor.

A side note: a colleague at 1&1 runs a Jessie distro kernel on an internal backup system with several thousands of servers and about 15 billions of inodes in ext4 filesystem instances. He has noticed an ext4 bug which triggers extremely rarely under very weird conditions. Therefore I looked into the Jessie and tried to get the sources in a clearly defined state.

This turned out more complicated than expected.

It looks like the Debian Jessie kernel flavor is based on an unmaintained (according to some Wiki article) Ubuntu fork of upstream kernel 3.16.7, while upstream is at 3.16.36 now. I looked first into the Debian kernel patch git at Alioth, and later into the corresponding Ubuntu base (where it seems to be based on). I was confused. It is all else but easy to determinie which patches are in and which not.

Personally, I cannot recommend such a kernel (fork of a seemingly unmaintained fork). I am preferring vanilla kernels from Linus, and in git form instead of these Debian quilt stacks. There I know how the developers are working. In my production area, I am using vanilla 3.14 as a base at the moment, because Greg is maintaining it,  and because a maintained grsecurity patch from Spender exists for it (I need this due to some special reasons).

You may ask Benjamin Kübler, who has a fork of mars here at github under "bkuebler". He has some generic script which turns (almost) any Debian kernel into a MARS-prepatched kernel via the Debian way. I know that he already built some Jessie kernel this way, but I am not in the details. He is also using MARS for some years now.

I would be glad if he (probably with help of some further people) would be officially maintaining a Debian-based kernel for MARS, or even a vanilla-based alternative. Please ask him. The more people are asking, the better the chances ;)

Cheers,

Thomas

**Comment by onlyjob** [comment]
> unfortunately current Debian stable release Jessie ships with 3.16...

Which is not a problem if you use official [backports](https://backports.debian.org/Instructions/) repository where kernel 4.6 is available for _Jessie_.

**Comment by schoebel** [comment]
hi Dmitry,

thanks for the hint. This means I should prioritize MARS support for kernel 4.6. I only tested up to kernel 4.4 until now. This has nothing to do with pre-patches, but with (potential) changes in the block layer of the kernel itself. I will have to look into it. Thanks for the hint.

**Comment by onlyjob** [comment]
No worries, Thomas. :)
By the way we have a packaging request to introduce _mars_ to Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770247

**Comment by schoebel** [comment]
Notice: the new development branch WIP-0.1-portability contains adapted _miminum_ pre-patches for all LTS kernels as displayed on kernel.org, from 3.2.x to 4.7.x. In difference to the old _generic_ pre-patch, only a few syscalls are EXPORT_SYMBOL()ed, which is better for security reasons.

Please prefer the new _minimum_ pre-patches after they are stable.

This weekend an automated meta-testsuite is running. It will loop over all mentioned vanilla kernels.

Hopefully, I can release this next week as mars0.1stable31.

After that, I will restart my old work on a portability layer which hopefully results in a completely pre-patch-less MARS, although slighly less performant because it uses SIO instead of AIO, and probably for less different kernel versions.

After that, ports to kernel 4.8 are the next step in the maintainance nightmare. The block layer interface of the kernel got some major changes once again.

**Comment by subbergunz** [comment]
This should be closed or merged with issue 21:

https://github.com/schoebel/mars/issues/21

**Comment by schoebel** [comment]
Yes, it has been addressed long ago.
