### ISSUE TITLE
"mars_config.h" not being generated

### ISSUE THREAD

**Issue by hbjcr** [schoebel/mars#15]
I've tried to compile multiple versions of the kernel but I always get the same error message:

`
block/mars/kernel/brick_say.h:29:25: fatal error: mars_config.h: No such file or directory
`

I found a comment in the "block/mars/kernel/Kbuild" file which indicates: `# mars_config.h is generated by a simple Kconfig parser (gen_config.pl)` but I don't really know what am I doing wrong to prevent this script from executing.

**Comment by schoebel** [comment]
Hi,

the gen_config.pl is 1&1 specific and is not intended for general use. Thus MARS _should_ also work without it, but according to your complait does not.

Please tell me: which version of MARS (commit ID), in combination with exactly which kernel (base commit ID before the pre-patch is applied)?

Please also send me your .config to my published email, then I should have everything to reproduce it exactly for you and fix it.

Cheers,

Thomas

**Comment by hbjcr** [comment]
I'll send the .config file to your email. Here is also a step-by-step document on what I'm doing.

As I said previously, the error shows up with multiple kernels and multiple MARS versions combinations. I decided to document the case I've tested the most:

1. Download a Ubuntu Server 14.04 image (ubuntu-14.04.5-server-amd64.iso). Install all the tools required to compile the kernel.

2. This OS comes with kernel 3.13 which doesn't appears in the list of pre-patch folders, so rather than messing around with the patch files I decided to bring the kernel up to a compatible version (e.g. Utopic Unicorn - 3.16):
`
sudo apt-get install linux-generic-lts-vivid
`
This installs kernel 3.16.0.77.68; more details can be found here: http://packages.ubuntu.com/trusty/kernel/linux-generic-lts-utopic

3. Server then requires a reboot to apply the kernel, then I then download the kernel source code with the following command:
`
apt-get source linux-image-$(uname -r)
`
Which downloads the following kernel source files: http://packages.ubuntu.com/trusty-updates/amd64/linux-image-3.16.0-77-generic/filelist

_At this point, I can compile the without problems (make oldconfig followed by make deb-pkg to generate the .deb packages)_

4. I then proceed to clone the MARS github project under the block folder. I've tried two different methods:

Using the default branch (points to commit https://github.com/schoebel/mars/commit/e5647b7a9b1aa2568cf11e794002c6cce5b1c9d0)
git clone https://github.com/schoebel/mars

Using the 0.2 branch (points to commit https://github.com/schoebel/mars/commit/68c2267ef3a0bc8175bfdfeda6621593b2eb17cb)
git clone -b mars0.2.y https://github.com/schoebel/mars

Keep in mind at this point I've tried the same next steps while using both MARS versions with multiple kernel versions...

5. Apply the pre-patches for the current kernel:

`
patch -p1 < /[home folder]/mars/linux-[kernel version]/block/mars/pre-patches/vanilla-[kernel version]/*-for-in-tree-build.patch
`

I've also tried excluding this other patch with the same result (compilation error):
`
patch -p1 < /[home folder]/mars/linux-[kernel version]/block/mars/pre-patches/vanilla-[kernel version]/0001-mars-minimum-pre-patch-for-mars.patch
`

6. Compile the kernel

`make oldconfig`
`make -j16 deb-pkg`

Something that may help at this point is that if I exclude the MARS module from the compilation (storage system MARS (EXPERIMENTAL) (MARS) [N/m/y/?] (NEW)) then everything works OK (deb packages are generated without problem). But if I include the MARS module then the error I sent previously shows up.

**Comment by schoebel** [comment]
Since I have no Ubuntu, I just quickly tried with a git-based vanilla kernel 3.16.43 (git checkout linux-3.16.y) and your .config (make oldconfig and leave everything else at the default) using the following variants:

1) Only the minimum pre-patch for vanilla 3.16, nothing else. This variant is meant for out-of-tree DKMS builds or similar.

After restarting the compile, it compiled without problems. But of course this does not build the MARS kernel module, it just prepares for a _later_ / separate DKMS build or some other out-of-tree build method.

Please notice that the gen_config.pl is used internally at 1&1 for some strange out-of-tree build (without DKMS).

Also notice that for any out-of-tree build you should not use the kernel block/ directoy but some other fresh directory somewhere else (typically distro-specific).

The 1&1-specific gen_config.pl and its mars_config.h output is _not_ intended for intree builds at all. It was not programmed by me, but by somebody else but I now have to maintain it ;)

I would be pleased if somebody from the community would maintain it and/or would instead make MARS to compile bullet-proof with whatever kernel on earth ;)

2) _After_ the generic pre-patch, the patch for intree build is applied _additionally_ (in this order, which deviates from your description). Then I cloned the master branch of MARS into block/ which is the most stable / proven code at the moment.

This also builds without problems (after additionally enabling MARS in the Kconfig of course).

Notice that the intree kernel makefile generates an internal buildtag.h which is not the same as the mars_config.h produced by the 1&1 specific gen_config.pl.

3) In order to more exactly reproduce your description, I made a fresh "git checkout" of the build tree, and applied both patches in reverse order.

There is no difference to before (as expected).

So I guess the problem is somewhere at Ubuntu.

My guess is that something sets KBUILD_EXTMOD and thus produces an unwanted mars_config.h or similar.

Thanks to your very precise description, I should be able to reproduce it, but I will need some time for installing Ubuntu at some VM.

Please be patient; I will try to make the compilation bullet-proof for whatever flavour of Linux (if nobody else does it).

In the meantime, you could try to remove the wrong mars_config.h by hand and try again. It should not be generated at all. Perhaps it might be a leftover from failed earlier attempts.

For an intree build, you may also just remove the whole Kbuild section which create mars_config.h then it should no longer be generated by accident :)

In case of success, please report your solution here for saving me (and other people) some time.

**Comment by schoebel** [comment]
What I forgot to mention: of course you must always compile MARS as a module (whether the module is built in-tree or out-of-tree). This is needed because /mars must be mounted _before_ the kernel module can be started.

Saying "y" to CONFIG_MARS could also trigger your problem.

**Comment by hbjcr** [comment]
According to [kconfig's documentation](https://www.kernel.org/doc/Documentation/kbuild/kconfig-language.txt), you can force a dependency to be compiled as a module only:

```
Build as module only
~~~~~~~~~~~~~~~~~~~~
To restrict a component build to module-only, qualify its config symbol
with "depends on m".  E.g.:

config FOO
	depends on BAR && m

limits FOO to module (=m) or disabled (=n).
```

I think this could be an improvement to the existing kconfig file or simply change the [default value](https://github.com/schoebel/mars/blob/master/kernel/Kconfig) from n to m?

Your response clarified a lot of questions I had. I'll do some testing and report back soon.

**Comment by hbjcr** [comment]
I was able to get MARS to work on Ubuntu 14.04. I've documented the steps [here](https://github.com/hbjcr/mars_docs) in case someone else might want to take a look.
